### ISSUE TITLE
Cannot open the new template in Designer

### ISSUE THREAD

**Issue by madhatta-ct** [wazuh/wazuh-cloudformation#21]
I am no longer able to open the template in the AWS designer

 01/10/2019, 14:59:09 - Cannot render the template because of an error.: YAMLException: duplicated mapping key at line 1868, column 1: ^

**Comment by madhatta-ct** [comment]
Found the issue, the below is duplicated at the end of the file.
Sorry, I'm new to Git, not sure if I can commit, but thought I help point it out :)

  Centos:
    Description: Elastic Stack and Wazuh versions
    Value: !GetAtt
      - Centos
      - PublicIp

**Comment by manuasir** [comment]
Hello @madhatta-ct ,

Thanks for reporting this! We will review and fix it ASAP.

Cheers

**Comment by manuasir** [comment]
Fixed in #46 . Thanks so much for reporting this @madhatta-ct :smiley:
