### ISSUE TITLE
Auditd rules fix

### ISSUE THREAD

**Issue by t0wb0at** [wazuh/wazuh-cloudformation#30]
Hello, dear Wazuh team!

I found that auditd rules that `wazuh-cloudformation/wazuh/cluster/wazuh_cf_worker.sh` and ` wazuh-cloudformation/wazuh/cluster/wazuh_cf_master.sh ` creates are not correct because of the wrong user:
```
the_uid=$(id -u wazuh)
```
Should it be changed to this?:
```
the_uid=$(id -u ossec)
```
Thanks!

**Comment by manuasir** [comment]
Hello @t0wb0at,

In that fragment of code, we select the user whose actions and commands we want to be monitored by Audit. For this case, we use `wazuh` (the SSH user) so it's not very verbose.

I hope that helps,
Regards

**Comment by t0wb0at** [comment]
Hi, @manuasir!

Ok, thanks for the clarification! 
I hope I'll be more useful for the Wazuh project next time)
Thanks for your amazing job!
