### ISSUE TITLE
Add the ability to deploy a production-ready cluster

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-cloudformation#51]
Hi team,

Currently, we provide a way to deploy a specific environment with several customized use cases installed on different agents. The main goal of this task is to implement the ability to deploy a production-ready cluster that includes:

- [x] Wazuh cluster of 2 manager nodes.
- [x] Secured Elasticsearch cluster of 3 nodes (XPack security).
- [x] Secured Kibana interface.
- [x] Agents can be registered and report to the cluster using a load balancer.
- [x] Optionally, include Route53 records.
- [x] Related documentation

The template should support as many parameters as possible in order to gain flexibility. Also, this environment should be started with the default configuration.

Regards

**Comment by Zenidd** [comment]
### Status update
- New repo directories distribution to separate demo and new production-ready environments.
```
├── demo
│   ├── deploy.sh
│   ├── elastic
│   ├── images
│   ├── README.md
│   ├── splunk
│   ├── wazuh
│   └── wazuh_template.yml
├── production
│   ├── deploy.sh
│   ├── elastic
│   ├── parameters.json
│   ├── README.md
│   ├── splunk
│   ├── wazuh
│   └── wazuh_template.yml
└── README.md
```
- The production-ready environment includes a parameters file (`parameters.json`) with placeholders to ease the environment set up.
- Related draft PR: https://github.com/wazuh/wazuh-cloudformation/pull/53

**Comment by Zenidd** [comment]
### Status update

- **Testing branch**: [feature-51-prod-ready-cluster-dev](https://github.com/wazuh/wazuh-cloudformation/tree/feature-51-prod-ready-cluster-dev).
- Packages/sources install modes.
- Simpler provisioning scripts that do not contain specific use cases intended for demo environments.
-  Kibana-Elastic mixed node: solving `JavaScript heap out of memory` errors during the Kibana plugin optimization on the provision stage.

**Comment by Zenidd** [comment]
### Status April 14, 2020

- The development branch has been updated: [feature-51-prod-ready-cluster](https://github.com/wazuh/wazuh-cloudformation/tree/feature-51-prod-ready-cluster)
  - The `demo` and `production` environments have been bumped to v3.12.2
  - Fixing minor errors and removing agents and custom configuration related options for production environment.
  -  **Solved** the errors during the Kibana optimize in both  `demo` and `production` environments.

- Working on the route53 records for the template.

**Comment by Zenidd** [comment]
### Status April 15, 2020

- The development branch has been updated: [feature-51-prod-ready-cluster](https://github.com/wazuh/wazuh-cloudformation/tree/feature-51-prod-ready-cluster)
#### Route 53 records b6405e4bfebd061e8d3f51bc89b4b55893bed680
  - The template now includes conditional route53 records. This feature is can be enabled/disabled through the `EnableDNSRecord` parameter.
  - When enabled, the public-facing loadbalancer, elastic stack and Wazuh nodes have associated DNS records.
- The `Subdomain` parameter sets the subdomain name for the loadbalancer.
- `HostedZoneName` sets the parent domain for the loadbalancer and the instances.
- The subdomain name is fixed for the Elastic Stack and Wazuh nodes and corresponds to the instances names.
#### Documentation 91d1b0fed9e79116f14a052da9cf82fbef8b8b65
- Improved documentation for production environment and modified the base repo documentation
#### Example template included in the production environment
The following template contains an example list of parameters and value placeholders:
<details>
  <summary>Click to expand!</summary>


```json
[{
    "ParameterKey": "ElasticWazuhVersion",
    "ParameterValue": "<ElasticWazuhVersion>"
},
{
    "ParameterKey": "WazuhInstanceType",
    "ParameterValue": "t2.medium"
},
{
    "ParameterKey": "InstallType",
    "ParameterValue": "<InstallType>"
},
{
    "ParameterKey": "ElasticInstanceType",
    "ParameterValue": "t2.large"
},
{
    "ParameterKey": "KibanaInstanceType",
    "ParameterValue": "t2.large"
},
{
    "ParameterKey": "SshUsername",
    "ParameterValue": "<SshUsername>"
},
{
    "ParameterKey": "SshPassword",
    "ParameterValue": "<SshPassword>"
},
{
    "ParameterKey": "WazuhServerPort",
    "ParameterValue": "1514"
},
{
    "ParameterKey": "WazuhRegistrationPort",
    "ParameterValue": "1515"
},
{
    "ParameterKey": "WazuhRegistrationPassword",
    "ParameterValue": "<WazuhRegistrationPassword>"
},
{
    "ParameterKey": "WazuhApiPort",
    "ParameterValue": "55000"
},
{
    "ParameterKey": "WazuhApiAdminUsername",
    "ParameterValue": "<WazuhApiAdminUsername>"
},
{
    "ParameterKey": "WazuhApiAdminPassword",
    "ParameterValue": "<WazuhApiAdminPassword>"
},
{
    "ParameterKey": "KeyPairName",
    "ParameterValue": "<KeyPairName>"
},
{
    "ParameterKey": "AvailabilityZone",
    "ParameterValue": "<AvailabilityZone>"
},
{
    "ParameterKey": "SSLCertificateARN",
    "ParameterValue": "<SSLCertificateARN>"
},
{
    "ParameterKey": "EnableDNSRecord",
    "ParameterValue": "disabled"
},
{
    "ParameterKey": "Subdomain",
    "ParameterValue": "<Subdomain>"
},
{
    "ParameterKey": "HostedZoneName",
    "ParameterValue": "<HostedZoneName>"
}
]
```

</details>
