### ISSUE TITLE
SubnetElasticsearch currently not used in wazuh_template.yml

### ISSUE THREAD

**Issue by troal** [wazuh/wazuh-cloudformation#7]
Hi,
It seems "SubnetId: !Ref SubnetElasticsearch" is currently not yet used in your wazuh_template.yml.
Could else use it for the elastic cluster or remove the unused ressources linked to it?
Thanks!

**Comment by manuasir** [comment]
Hello @troal ,

Thanks for reporting this, I'll commit the fix as soon as possible. Meanwhile, you can use the subnet for the Elasticsearch cluster.

Regards

**Comment by manuasir** [comment]
Hello @troal ,

This was fixed here https://github.com/wazuh/wazuh-cloudformation/commit/cf701d631f75acb6fe0114e0fcfad1bc8ef5bd76. You can get the latest `v3.9.2_7.1.1` branch, which is currently being tested but it will be merged to the `master` branch soon.

Thanks again for reporting this, don't hesitate to open a new issue if you need it.

Cheers
