### ISSUE TITLE
Apply Wazuh daemons name changing to wazuh-cloudformation

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-cloudformation#79]
## Description
Hello team. 

According to the changes proposed at wazuh/wazuh#6741, the following daemons will be renamed or totally removed from new Wazuh installations.

- Unix:
  - `ossec-agentd` -> `wazuh-agentd`
  - `ossec-agentlessd` -> `wazuh-agentlessd`
  - `ossec-analysisd` -> `wazuh-analysisd`
  - `ossec-authd` -> `wazuh-authd`
  - `ossec-csyslogd` -> `wazuh-csyslogd`
  - `ossec-dbd` -> `wazuh-dbd`
  - `ossec-execd` -> `wazuh-execd`
  - `ossec-integratord` -> `wazuh-integratord`
  - `ossec-logcollector` -> `wazuh-logcollector`
  - `ossec-maild` -> `wazuh-maild`
  - `ossec-monitord` -> `wazuh-monitord`
  - `ossec-remoted` -> `wazuh-remoted`
  - `ossec-reportd` -> `wazuh-reportd`
  - `ossec-syscheckd` -> `wazuh-syscheckd`

- Windows:
  - `ossec-agent.exe` -> `wazuh-agent.exe`
  - `ossec-agent-eventchannel.exe` -> `wazuh-agent-eventchannel.exe`
  - `ossec-rootcheck.exe` -> deprecated

I saw references to these daemons in this repo. Please, update these references according to the proposed renaming.

**Comment by neonmei** [comment]
Hello @TomasTurina,
I did a quickcheck with [ripgrep](https://github.com/BurntSushi/ripgrep) and found no references the mentioned daemons.

```
$ rg ossec-agentd
$ rg ossec-agentlessd
$ rg ossec-analysisd
$ rg ossec-authd
$ rg ossec-csyslogd
$ rg ossec-dbd
$ rg ossec-execd
$ rg ossec-integratord
$ rg ossec-logcollector
$ rg ossec-maild
$ rg ossec-monitord
$ rg ossec-remoted
$ rg ossec-reportd
$ rg ossec-syscheckd
$ rg ossec-agent.exe
$ rg ossec-agent-eventchannel.exe
$ rg ossec-rootcheck.exe
```

If you notice that I missed something, please  feel free to ropen the issue. Thanks!
