### ISSUE TITLE
Rename wazuh-cloudformation users and groups according to the new Wazuh naming standard

### ISSUE THREAD

**Issue by alromeros** [wazuh/wazuh-cloudformation#84]
### Description

Hi team,

The goal of this issue is to rename all the references to the legacy users and groups in the **wazuh-cloudformation** repository, according to the new Wazuh naming standard described in https://github.com/wazuh/wazuh/issues/7646.

**Users to modify**
- `ossec`→ `wazuh`
- `ossecm` → `wazuh` _(Not present in this repository)_
- `ossecr` → `wazuh` _(Not present in this repository)_

**Group to modify**
- `ossec` → `wazuh`

### Relevant files

After a quick research, some files that appear to be relevant to this issue are:

- **`ossec` main occurrences:**

    - `./demo/wazuh/cluster/wazuh_cf_master.sh`

**Comment by vcerenu** [comment]
Changed the chown command that modified the files to ossec: ossec by wazuh: wazuh in demo/wazuh/cluster/wazuh_cf_master.sh line 157
